export const ICON_FILENAME_TO_SERVICE = {
  AmazonAthena: 'Amazon Athena',
  AmazonCloudSearch: 'Amazon CloudSearch',
  AmazonDataFirehose: 'Amazon Data Firehose',
  AmazonDataZone: 'Amazon DataZone',
  AmazonEMR: 'Amazon EMR',
  AmazonFinSpace: 'Amazon FinSpace',
  AmazonKinesis: 'Amazon Kinesis',
  AmazonKinesisDataStreams: 'Amazon Kinesis Data Streams',
  AmazonKinesisVideoStreams: 'Amazon Kinesis Video Streams',
  AmazonManagedServiceforApacheFlink: 'Amazon Managed Service for Apache Flink',
  AmazonManagedStreamingforApacheKafka: 'Amazon MSK',
  AmazonOpenSearchService: 'Amazon OpenSearch Service',
  AmazonQuickSight: 'Amazon QuickSight',
  AmazonRedshift: 'Amazon Redshift',
  AmazonSageMaker: 'Amazon SageMaker',
  AWSCleanRooms: 'AWS Clean Rooms',
  AWSDataExchange: 'AWS Data Exchange',
  AWSEntityResolution: 'AWS Entity Resolution',
  AWSGlue: 'AWS Glue',
  AWSGlueDataBrew: 'AWS Glue DataBrew',
  AWSLakeFormation: 'AWS Lake Formation',
  AmazonAppFlow: 'Amazon AppFlow',
  AmazonEventBridge: 'Amazon EventBridge',
  AmazonManagedWorkflowsforApacheAirflow: 'Amazon MWAA',
  AmazonMQ: 'Amazon MQ',
  AmazonSimpleNotificationService: 'Amazon SNS',
  AmazonSimpleQueueService: 'Amazon SQS',
  AWSAppSync: 'AWS AppSync',
  AWSB2BDataInterchange: 'AWS B2B Data Interchange',
  AWSExpressWorkflows: 'AWS Express Workflows',
  AWSStepFunctions: 'AWS Step Functions',
  AmazonAugmentedAIA2I: 'Amazon Augmented AIA2I',
  AmazonBedrock: 'Amazon Bedrock',
  AmazonCodeGuru: 'Amazon CodeGuru',
  AmazonCodeWhisperer: 'Amazon CodeWhisperer',
  AmazonComprehend: 'Amazon Comprehend',
  AmazonComprehendMedical: 'Amazon Comprehend Medical',
  AmazonDevOpsGuru: 'Amazon DevOps Guru',
  AmazonElasticInference: 'Amazon Elastic Inference',
  AmazonForecast: 'Amazon Forecast',
  AmazonFraudDetector: 'Amazon Fraud Detector',
  AmazonKendra: 'Amazon Kendra',
  AmazonLex: 'Amazon Lex',
  AmazonLookoutforEquipment: 'Amazon Lookout for Equipment',
  AmazonLookoutforMetrics: 'Amazon Lookout for Metrics',
  AmazonLookoutforVision: 'Amazon Lookout for Vision',
  AmazonMonitron: 'Amazon Monitron',
  AmazonNova: 'Amazon Nova',
  AmazonPersonalize: 'Amazon Personalize',
  AmazonPolly: 'Amazon Polly',
  AmazonQ: 'Amazon Q',
  AmazonRekognition: 'Amazon Rekognition',
  AmazonSageMakerAI: 'Amazon SageMaker AI',
  AmazonSageMakerGroundTruth: 'Amazon SageMaker Ground Truth',
  AmazonSageMakerStudioLab: 'Amazon SageMaker Studio Lab',
  AmazonTextract: 'Amazon Textract',
  AmazonTranscribe: 'Amazon Transcribe',
  AmazonTranslate: 'Amazon Translate',
  ApacheMXNetonAWS: 'Apache MX Net on AWS',
  AWSAppStudio: 'AWS App Studio',
  AWSDeepComposer: 'AWS DeepComposer',
  AWSDeepLearningAMIs: 'AWS Deep Learning AMIs',
  AWSDeepLearningContainers: 'AWS Deep Learning Containers',
  AWSDeepLens: 'AWS Deep Lens',
  AWSDeepRacer: 'AWS DeepRacer',
  AWSHealthImaging: 'AWS HealthImaging',
  AWSHealthLake: 'AWS HealthLake',
  AWSHealthOmics: 'AWS HealthOmics',
  AWSHealthScribe: 'AWS Health Scribe',
  AWSNeuron: 'AWS Neuron',
  AWSPanorama: 'AWS Panorama',
  PyTorchonAWS: 'PyTorch on AWS',
  TensorFlowonAWS: 'TensorFlow on AWS',
  AmazonManagedBlockchain: 'Amazon Managed Blockchain',
  AmazonQuantumLedgerDatabase: 'Amazon Quantum Ledger Database',
  AlexaForBusiness: 'Alexa For Business',
  AmazonChime: 'Amazon Chime',
  AmazonChimeSDK: 'Amazon Chime SDK',
  AmazonConnect: 'Amazon Connect',
  AmazonPinpoint: 'Amazon Pinpoint',
  AmazonPinpointAPIs: 'Amazon Pinpoint APIs',
  AmazonSimpleEmailService: 'Amazon Simple Email Service',
  AmazonWorkDocs: 'Amazon WorkDocs',
  AmazonWorkDocsSDK: 'Amazon WorkDocs SDK',
  AmazonWorkMail: 'Amazon WorkMail',
  AWSAppFabric: 'AWS AppFabric',
  AWSEndUserMessaging: 'AWS End User Messaging',
  AWSSupplyChain: 'AWS Supply Chain',
  AWSWickr: 'AWS Wickr',
  AWSBillingConductor: 'AWS Billing Conductor',
  AWSBudgets: 'AWS Budgets',
  AWSCostandUsageReport: 'AWS Costand Usage Report',
  AWSCostExplorer: 'AWS Cost Explorer',
  ReservedInstanceReporting: 'Reserved Instance Reporting',
  SavingsPlans: 'Savings Plans',
  AmazonDCV: 'Amazon DCV',
  AmazonEC2: 'Amazon EC2',
  AmazonEC2AutoScaling: 'Amazon EC2 Auto Scaling',
  AmazonEC2ImageBuilder: 'Amazon EC2 Image Builder',
  AmazonLightsail: 'Amazon Lightsail',
  AmazonLightsailforResearch: 'Amazon Lightsail for Research',
  AWSAppRunner: 'AWS App Runner',
  AWSBatch: 'AWS Batch',
  AWSComputeOptimizer: 'AWS Compute Optimizer',
  AWSElasticBeanstalk: 'AWS Elastic Beanstalk',
  AWSLambda: 'AWS Lambda',
  AWSLocalZones: 'AWS Local Zones',
  AWSNitroEnclaves: 'AWS Nitro Enclaves',
  AWSOutpostsfamily: 'AWS Outposts family',
  AWSOutpostsrack: 'AWS Outposts rack',
  AWSOutpostsservers: 'AWS Outposts servers',
  AWSParallelCluster: 'AWS Parallel Cluster',
  AWSParallelComputingService: 'AWS Parallel Computing Service',
  AWSServerlessApplicationRepository: 'AWS Serverless Application Repository',
  AWSSimSpaceWeaver: 'AWS Sim Space Weaver',
  AWSWavelength: 'AWS Wavelength',
  Bottlerocket: 'Bottlerocket',
  ElasticFabricAdapter: 'Elastic Fabric Adapter',
  NICEEnginFrame: 'NICE EnginFrame',
  AmazonECSAnywhere: 'Amazon ECS Anywhere',
  AmazonEKSAnywhere: 'Amazon EKS Anywhere',
  AmazonEKSCloud: 'Amazon EKS Cloud',
  AmazonEKSDistro: 'Amazon EKS Distro',
  AmazonElasticContainerRegistry: 'Amazon ECR',
  AmazonElasticContainerService: 'Amazon ECS',
  AmazonElasticKubernetesService: 'Amazon EKS',
  AWSFargate: 'AWS Fargate',
  RedHatOpenShiftServiceonAWS: 'Red Hat OpenShift Serviceon AWS',
  AWSActivate: 'AWS Activate',
  AWSIQ: 'AWS IQ',
  AWSManagedServices: 'AWS Managed Services',
  AWSProfessionalServices: 'AWS Professional Services',
  AWSrePost: 'AWS rePost',
  AWSrePostPrivate: 'AWS rePost Private',
  AWSSupport: 'AWS Support',
  AWSTrainingCertification: 'AWS Training Certification',
  AmazonAurora: 'Amazon Aurora',
  AmazonDocumentDB: 'Amazon DocumentDB',
  AmazonDynamoDB: 'Amazon DynamoDB',
  AmazonElastiCache: 'Amazon ElastiCache',
  AmazonKeyspaces: 'Amazon Keyspaces',
  AmazonMemoryDB: 'Amazon MemoryDB',
  AmazonNeptune: 'Amazon Neptune',
  AmazonRDS: 'Amazon Relational Database Service',
  AmazonTimestream: 'Amazon Timestream',
  AWSDatabaseMigrationService: 'AWS Database Migration Service',
  OracleDatabaseatAWS: 'Oracle Databaseat AWS',
  AmazonCodeCatalyst: 'Amazon CodeCatalyst',
  AmazonCorretto: 'Amazon Corretto',
  AWSCloud9: 'AWS Cloud9',
  AWSCloudControlAPI: 'AWS Cloud Control API',
  AWSCloudDevelopmentKit: 'AWS Cloud Development Kit',
  AWSCloudShell: 'AWS CloudShell',
  AWSCodeArtifact: 'AWS CodeArtifact',
  AWSCodeBuild: 'AWS CodeBuild',
  AWSCodeCommit: 'AWS CodeCommit',
  AWSCodeDeploy: 'AWS CodeDeploy',
  AWSCodePipeline: 'AWS CodePipeline',
  AWSCommandLineInterface: 'AWS Command Line Interface',
  AWSFaultInjectionService: 'AWS Fault Injection Service',
  AWSInfrastructureComposer: 'AWS Infrastructure Composer',
  AWSToolsandSDKs: 'AWS Toolsand SDKs',
  AWSXRay: 'AWS X-Ray',
  AmazonAppStream2: 'Amazon AppStream 2.0',
  AmazonWorkSpacesFamily: 'Amazon WorkSpaces Family',
  AmazonLocationService: 'Amazon Location Service',
  AWSAmplify: 'AWS Amplify',
  AWSDeviceFarm: 'AWS Device Farm',
  AmazonGameLift: 'Amazon Game Lift',
  Open3DEngine: 'Open3DEngine',
  AWSMarketplace: 'AWS Marketplace',
  AWSMarketplaceDark: 'AWS Marketplace Dark',
  AWSIoTAnalytics: 'AWS IoT Analytics',
  AWSIoTButton: 'AWS IoT Button',
  AWSIoTCore: 'AWS IoT Core',
  AWSIoTDeviceDefender: 'AWS IoT Device Defender',
  AWSIoTDeviceManagement: 'AWS IoT Device Management',
  AWSIoTEvents: 'AWS IoT Events',
  AWSIoTExpressLink: 'AWS IoT ExpressLink',
  AWSIoTFleetWise: 'AWS IoT FleetWise',
  AWSIoTGreengrass: 'AWS IoT Greengrass',
  AWSIoTSiteWise: 'AWS IoT SiteWise',
  AWSIoTTwinMaker: 'AWS IoT TwinMaker',
  FreeRTOS: 'Free RTOS',
  AmazonCloudWatch: 'Amazon CloudWatch',
  AmazonManagedGrafana: 'Amazon Managed Grafana',
  AmazonManagedServiceforPrometheus: 'Amazon Managed Service for Prometheus',
  AWSAppConfig: 'AWS AppConfig',
  AWSApplicationAutoScaling: 'AWS Application Auto Scaling',
  AWSAutoScaling: 'AWS Auto Scaling',
  AWSBackintAgent: 'AWS Backint Agent',
  AWSChatbot: 'AWS Chatbot',
  AWSCloudFormation: 'AWS CloudFormation',
  AWSCloudTrail: 'AWS CloudTrail',
  AWSConfig: 'AWS Config',
  AWSConsoleMobileApplication: 'AWS Console Mobile Application',
  AWSControlTower: 'AWS Control Tower',
  AWSDistroforOpenTelemetry: 'AWS Distro for Open Telemetry',
  AWSHealthDashboard: 'AWS Health Dashboard',
  AWSLaunchWizard: 'AWS Launch Wizard',
  AWSLicenseManager: 'AWS License Manager',
  AWSManagementConsole: 'AWS Management Console',
  AWSOrganizations: 'AWS Organizations',
  AWSProton: 'AWS Proton',
  AWSResilienceHub: 'AWS Resilience Hub',
  AWSResourceExplorer: 'AWS Resource Explorer',
  AWSServiceCatalog: 'AWS Service Catalog',
  AWSServiceManagementConnector: 'AWS Service Management Connector',
  AWSSystemsManager: 'AWS Systems Manager',
  AWSTelcoNetworkBuilder: 'AWS Telco Network Builder',
  AWSTrustedAdvisor: 'AWS Trusted Advisor',
  AWSUserNotifications: 'AWS User Notifications',
  AWSWellArchitectedTool: 'AWS Well Architected Tool',
  AmazonElasticTranscoder: 'Amazon Elastic Transcoder',
  AmazonInteractiveVideoService: 'Amazon Interactive Video Service',
  AWSDeadlineCloud: 'AWS Deadline Cloud',
  AWSElementalAppliancesSoftware: 'AWS Elemental Appliances Software',
  AWSElementalConductor: 'AWS Elemental Conductor',
  AWSElementalDelta: 'AWS Elemental Delta',
  AWSElementalLink: 'AWS Elemental Link',
  AWSElementalLive: 'AWS Elemental Live',
  AWSElementalMediaConnect: 'AWS Elemental MediaConnect',
  AWSElementalMediaConvert: 'AWS Elemental MediaConvert',
  AWSElementalMediaLive: 'AWS Elemental MediaLive',
  AWSElementalMediaPackage: 'AWS Elemental MediaPackage',
  AWSElementalMediaStore: 'AWS Elemental MediaStore',
  AWSElementalMediaTailor: 'AWS Elemental MediaTailor',
  AWSElementalServer: 'AWS Elemental Server',
  AWSThinkboxDeadline: 'AWS Thinkbox Deadline',
  AWSThinkboxFrost: 'AWS Thinkbox Frost',
  AWSThinkboxKrakatoa: 'AWS Thinkbox Krakatoa',
  AWSThinkboxSequoia: 'AWS Thinkbox Sequoia',
  AWSThinkboxStoke: 'AWS Thinkbox Stoke',
  AWSThinkboxXMesh: 'AWS Thinkbox XMesh',
  AmazonElasticVMwareService: 'Amazon Elastic VMware Service',
  AWSApplicationDiscoveryService: 'AWS Application Discovery Service',
  AWSApplicationMigrationService: 'AWS Application Migration Service',
  AWSDataSync: 'AWS DataSync',
  AWSDataTransferTerminal: 'AWS Data Transfer Terminal',
  AWSMainframeModernization: 'AWS Mainframe Modernization',
  AWSMigrationEvaluator: 'AWS Migration Evaluator',
  AWSMigrationHub: 'AWS Migration Hub',
  AWSTransferFamily: 'AWS Transfer Family',
  AmazonAPIGateway: 'Amazon API Gateway',
  AmazonApplicationRecoveryController: 'Amazon Application Recovery Controller',
  AmazonCloudFront: 'Amazon CloudFront',
  AmazonRoute53: 'Amazon Route 53',
  AmazonVirtualPrivateCloud: 'Amazon Virtual Private Cloud',
  AmazonVPCLattice: 'Amazon VPC Lattice',
  AWSAppMesh: 'AWS App Mesh',
  AWSClientVPN: 'AWS Client VPN',
  AWSCloudMap: 'AWS Cloud Map',
  AWSCloudWAN: 'AWS Cloud WAN',
  AWSDirectConnect: 'AWS Direct Connect',
  AWSGlobalAccelerator: 'AWS Global Accelerator',
  AWSPrivate5G: 'AWS Private5G',
  AWSPrivateLink: 'AWS Private Link',
  AWSSitetoSiteVPN: 'AWS Site to Site VPN',
  AWSTransitGateway: 'AWS Transit Gateway',
  AWSVerifiedAccess: 'AWS Verified Access',
  ElasticLoadBalancing: 'Elastic Load Balancing',
  AmazonBraket: 'Amazon Braket',
  AWSRoboMaker: 'AWS RoboMaker',
  AWSGroundStation: 'AWS Ground Station',
  AmazonCloudDirectory: 'Amazon Cloud Directory',
  AmazonCognito: 'Amazon Cognito',
  AmazonDetective: 'Amazon Detective',
  AmazonGuardDuty: 'Amazon GuardDuty',
  AmazonInspector: 'Amazon Inspector',
  AmazonMacie: 'Amazon Macie',
  AmazonSecurityLake: 'Amazon Security Lake',
  AmazonVerifiedPermissions: 'Amazon Verified Permissions',
  AWSArtifact: 'AWS Artifact',
  AWSAuditManager: 'AWS Audit Manager',
  AWSCertificateManager: 'AWS Certificate Manager',
  AWSCloudHSM: 'AWS CloudHSM',
  AWSDirectoryService: 'AWS Directory Service',
  AWSFirewallManager: 'AWS Firewall Manager',
  AWSIAMIdentityCenter: 'AWS IAM Identity Center',
  AWSIdentityandAccessManagement: 'AWS Identity and Access Management',
  AWSKeyManagementService: 'AWS KMS',
  AWSNetworkFirewall: 'AWS Network Firewall',
  AWSPaymentCryptography: 'AWS Payment Cryptography',
  AWSPrivateCertificateAuthority: 'AWS Private Certificate Authority',
  AWSResourceAccessManager: 'AWS Resource Access Manager',
  AWSSecretsManager: 'AWS Secrets Manager',
  AWSSecurityHub: 'AWS Security Hub',
  AWSSecurityIncidentResponse: 'AWS Security Incident Response',
  AWSShield: 'AWS Shield',
  AWSSigner: 'AWS Signer',
  AWSWAF: 'AWS WAF',
  AmazonEFS: 'Amazon EFS',
  AmazonElasticBlockStore: 'Amazon EBS',
  AmazonFileCache: 'Amazon File Cache',
  AmazonFSx: 'Amazon FSx',
  AmazonFSxforLustre: 'Amazon FSx for Lustre',
  AmazonFSxforNetAppONTAP: 'Amazon FSx for Net App ONTAP',
  AmazonFSxforOpenZFS: 'Amazon FSx for Open ZFS',
  AmazonFSxforWFS: 'Amazon FSx for WFS',
  AmazonS3onOutposts: 'Amazon S3 on Outposts',
  AmazonSimpleStorageService: 'Amazon S3',
  AmazonSimpleStorageServiceGlacier: 'Amazon S3 Glacier',
  AWSBackup: 'AWS Backup',
  AWSElasticDisasterRecovery: 'AWS Elastic Disaster Recovery',
  AWSSnowball: 'AWS Snowball',
  AWSSnowballEdge: 'AWS Snowball Edge',
  AWSStorageGateway: 'AWS Storage Gateway',
} as Record<string, string>

export const serviceAlternativeNames = {
  'Amazon SQS': 'Amazon Simple Queue Service',
  'Amazon SNS': 'Amazon Simple Notification Service',
  'Amazon ECS': 'Amazon Elastic Container Service',
  'Amazon EKS': 'Amazon Elastic Kubernetes Service',
  'Amazon EBS': 'Amazon Elastic Block Store',
  'Elastic File System': 'Amazon EFS',
} as Record<string, string>

export const SERVICE_TO_ICON_FILENAME = {
  'Amazon A2I': 'AmazonAugmentedAIA2I',
  'AWS Amplify (AWS Mobile SDK for Android)': 'AWSToolsandSDKs',
  'AWS AmplifyiOS (AWS Mobile SDK for iOS)': 'AWSToolsandSDKs',
  'Amazon Aurora DSQL': 'AmazonAurora',
  'AWS App2Container': 'Toolkit',
  'Auto Scaling': 'AWSAutoScaling',
  'Amazon Application Recovery Controller (ARC)':
    'AmazonApplicationRecoveryController',
  'AWS CLI': 'AWSCommandLineInterface',
  'Amazon Data Lifecycle Manager': 'AWSDatabaseMigrationService',
  'Amazon DocumentDB (with MongoDB compatibility)': 'AmazonDocumentDB',
  'Amazon GameLift Servers': 'AmazonGameLift',
  'Amazon WorkSpaces': 'AmazonWorkSpacesFamily',
  'Amazon WorkSpaces Core': 'AmazonWorkSpacesFamilyAmazonWorkSpacesCore',
  'Amazon WorkSpaces Secure Browser':
    'AmazonWorkSpacesFamilyAmazonWorkSpacesSecureBrowser',
  'AWS Well-Architected Tool': 'AWSWellArchitectedTool',
  'AWS Cloud Digital Interface SDK': 'AWSCloudDigitalInterface',
  'Amazon VPC': 'AmazonVirtualPrivateCloud',
  'AWS Blockchain Templates': 'Blockchain',
  'AWS VPN': ['AWSSitetoSiteVPN', 'AWSClientVPN'],
  'Toolkit for .NET Refactoring': 'Toolkit',
  'AWS Toolkit for Azure DevOps': 'Toolkit',
  'AWS Toolkit for JetBrains': 'Toolkit',
  'Toolkit for Visual Studio': 'Toolkit',
  'AWS Toolkit for Visual Studio Code': 'Toolkit',
  'AWS Training and Certification': 'AWSTrainingCertification',
  'AWS Account Management': 'AWSAccount',
  'Apache MXNet on AWS': 'ApacheMXNetonAWS',
  'AWS Billing and Cost Management': 'AWSBillingConductor',
  'Amazon DevOps Guru': 'AmazonDevOpsGuru',
  'Amazon WorkSpaces Thin Client': 'AmazonWorkSpacesFamilyAmazonWorkSpaces',
  'AWS WAF or AWS Shield?': ['AWSWAF', 'AWSShield'],
  'AWS Tools for PowerShell': 'Toolkit',
  'AWS Data Pipeline': 'Toolkit',
  'AWS Diagnostic Tools': 'Toolkit',
  'Amazon Elastic File System': 'AmazonEFS',
  'Amazon Bedrock or Amazon SageMaker AI?': [
    'AmazonBedrock',
    'AmazonSageMakerAI',
  ],
  'Choosing a database for your generative AI applications': 'Database',
  'Choosing a generative AI service': [
    'ArtificialIntelligence',
    'AmazonBedrock',
    'AmazonSageMakerAI',
    'AmazonQ',
  ],
  'Choosing a modern application strategy': [
    'Serverless',
    'Compute',
    'AmazonElasticContainerService',
    'AWSAppRunner',
    'AWSFargate',
    'AWSLambda',
    'AmazonElasticKubernetesService',
  ],
  'Choosing an AWS analytics service': 'Analytics',
  'Choosing an AWS application integration service': 'ApplicationIntegration',
  'Choosing an AWS cloud governance service': 'ManagementGovernance',
  'Choosing an AWS compute service': 'Compute',
  'Choosing an AWS container service': 'Containers',
  'Choosing an AWS cost management strategy': 'CloudFinancialManagement',
  'Choosing an AWS cryptography service': 'SecurityIdentityCompliance',
  'Choosing an AWS database service': 'Database',
  'Choosing an AWS identity service': [
    'SecurityIdentityCompliance',
    'AWSIdentityandAccessManagement',
    'AWSIAMIdentityCenter',
    'AmazonCognito',
    'AWSDirectoryService',
  ],
  'Choosing an AWS IoT service': 'InternetofThings',
  'Choosing an AWS monitoring and observability service':
    'SecurityIdentityCompliance',
  'Choosing an AWS machine learning service': 'ArtificialIntelligence',
  'Choosing AWS migration services and tools': 'MigrationModernization',
  'Choosing an AWS networking and content delivery service':
    'NetworkingContentDelivery',
  'Choosing an AWS storage service': 'Storage',
  'Choosing AWS frontend and mobile services': 'FrontEndWebMobile',
  'Choosing AWS security, identity, and governance services':
    'SecurityIdentityCompliance',
  'AWS CloudTrail or Amazon CloudWatch?': ['AWSCloudTrail', 'AmazonCloudWatch'],
  'AWS Crypto Tools': 'Toolkit',
  'AWS Systems Manager Incident Manager': 'AWSSystemsManagerIncidentManager',
  'Tag Editor': 'AWSServiceCatalog',
  'Tagging AWS Resources': 'AWSServiceCatalog',
  'Amazon SWF': 'AWSStepFunctions',
  'AWS End User Messaging SMS': 'AWSEndUserMessaging',
  'AWS End User Messaging Social': 'AWSEndUserMessaging',
  'AWS End User Messaging Push': 'AWSEndUserMessaging',
  FreeRTOS: 'FreeRTOS',
  'Amazon GameLift Streams': 'AmazonGameLiftStreams',
  'AWS Health': 'AWSHealthDashboard',
  'AWS Incident Detection and Response': 'AWSSecurityIncidentResponse',
  'AWS IoT Wireless': '',
  'Amazon Keyspaces (for Apache Cassandra)': 'AmazonKeyspaces',
  'Amazon Lightsail or Amazon EC2?': ['AmazonLightsail', 'AmazonEC2'],
  'Amazon Linux': '',
  'AWS Mobile SDK for Unity': 'AWSToolsandSDKs',
  'AWS OpsWorks': '',
  'AWS Outposts': 'AWSOutpostsrack',
  'Oracle Database@AWS': 'OracleDatabaseatAWS',
  'AWS ParallelCluster': 'AWSParallelCluster',
  'AWS Partner Central': '',
  'Porting Assistant for .NET': 'Toolkit',
  'AWS Pricing Calculator': 'Toolkit',
  'AWS Resource Groups': 'AWSResourceExplorer',
  'Amazon Q Developer in chat applications': 'AmazonQ',
  'Amazon QLDB': 'AmazonQuantumLedgerDatabase',
  'Red Hat OpenShift Service on AWS': 'RedHatOpenShiftServiceonAWS',
  'Research and Engineering Studio on AWS': 'Toolkit',
  'Amazon Route 53': 'AmazonRoute53',
  'AWS SAM': 'Toolkit',
  'AWS Schema Conversion Tool': 'Toolkit',
  'AWS SDK for Kotlin': 'AWSToolsandSDKs',
  'AWS SDK for .NET': 'AWSToolsandSDKs',
  'AWS SDK for C++': 'AWSToolsandSDKs',
  'AWS SDK for Go': 'AWSToolsandSDKs',
  'AWS SDK for Java': 'AWSToolsandSDKs',
  'AWS SDK for JavaScript': 'AWSToolsandSDKs',
  'AWS SDK for PHP': 'AWSToolsandSDKs',
  'AWS SDK for Python (Boto3)': 'AWSToolsandSDKs',
  'AWS SDK for Ruby': 'AWSToolsandSDKs',
  'SDK for Swift': 'AWSToolsandSDKs',
  'SDK for Rust': 'AWSToolsandSDKs',
  'SDK for SAP ABAP': 'AWSToolsandSDKs',
  'SDKs and Tools Reference Guide': 'AWSToolsandSDKs',
  'AWS Security Credentials': [
    'Credentials',
    'AWSIdentityAccessManagementLongTermSecurityCredential',
    'AWSIdentityAccessManagementTemporarySecurityCredential',
  ],
  'Security Documentation': 'SecurityIdentityCompliance',
  Serverless: 'Serverless',
  'AWS Service Endpoints': '',
  'Service Quotas': '',
  'Service Quotas reference': '',
  'AWS Sign-In': '',
  'Amazon Silk': '',
  'AWS SimSpace Weaver': 'AWSSimSpaceWeaver',
  'AWS Transform': 'AWSTransform',
  'Amazon Machine Learning': 'ArtificialIntelligence',
  'AWS Microservice Extractor for .NET': 'Toolkit',
  '': '',
} as Record<string, string | string[]>
