export const serviceNames = {
  AmazonAthena: 'Amazon Athena',
  AmazonCloudSearch: 'Amazon CloudSearch',
  AmazonDataFirehose: 'Amazon Data Firehose',
  AmazonDataZone: 'Amazon DataZone',
  AmazonEMR: 'Amazon EMR',
  AmazonFinSpace: 'Amazon FinSpace',
  AmazonKinesis: 'Amazon Kinesis',
  AmazonKinesisDataStreams: 'Amazon Kinesis Data Streams',
  AmazonKinesisVideoStreams: 'Amazon Kinesis Video Streams',
  AmazonManagedServiceforApacheFlink: 'Amazon Managed Service for Apache Flink',
  AmazonManagedStreamingforApacheKafka:
    'Amazon Managed Streaming for Apache Kafka',
  AmazonOpenSearchService: 'Amazon Open Search Service',
  AmazonQuickSight: 'Amazon QuickSight',
  AmazonRedshift: 'Amazon Redshift',
  AmazonSageMaker: 'Amazon SageMaker',
  AWSCleanRooms: 'AWS Clean Rooms',
  AWSDataExchange: 'AWS Data Exchange',
  AWSEntityResolution: 'AWS Entity Resolution',
  AWSGlue: 'AWS Glue',
  AWSGlueDataBrew: 'AWS Glue DataBrew',
  AWSLakeFormation: 'AWS Lake Formation',
  AmazonAppFlow: 'Amazon App Flow',
  AmazonEventBridge: 'Amazon Event Bridge',
  AmazonManagedWorkflowsforApacheAirflow:
    'Amazon Managed Workflows for Apache Airflow',
  AmazonMQ: 'Amazon MQ',
  AmazonSimpleNotificationService: 'Amazon Simple Notification Service',
  AmazonSimpleQueueService: 'Amazon Simple Queue Service',
  AWSAppSync: 'AWS AppSync',
  AWSB2BDataInterchange: 'AWS B2B Data Interchange',
  AWSExpressWorkflows: 'AWS Express Workflows',
  AWSStepFunctions: 'AWS Step Functions',
  AmazonAugmentedAIA2I: 'Amazon Augmented AIA2I',
  AmazonBedrock: 'Amazon Bedrock',
  AmazonCodeGuru: 'Amazon Code Guru',
  AmazonCodeWhisperer: 'Amazon CodeWhisperer',
  AmazonComprehend: 'Amazon Comprehend',
  AmazonComprehendMedical: 'Amazon Comprehend Medical',
  AmazonDevOpsGuru: 'Amazon DevOps Guru',
  AmazonElasticInference: 'Amazon Elastic Inference',
  AmazonForecast: 'Amazon Forecast',
  AmazonFraudDetector: 'Amazon Fraud Detector',
  AmazonKendra: 'Amazon Kendra',
  AmazonLex: 'Amazon Lex',
  AmazonLookoutforEquipment: 'Amazon Lookout for Equipment',
  AmazonLookoutforMetrics: 'Amazon Lookout for Metrics',
  AmazonLookoutforVision: 'Amazon Lookout for Vision',
  AmazonMonitron: 'Amazon Monitron',
  AmazonNova: 'Amazon Nova',
  AmazonPersonalize: 'Amazon Personalize',
  AmazonPolly: 'Amazon Polly',
  AmazonQ: 'Amazon Q',
  AmazonRekognition: 'Amazon Rekognition',
  AmazonSageMakerAI: 'Amazon SageMaker AI',
  AmazonSageMakerGroundTruth: 'Amazon SageMaker Ground Truth',
  AmazonSageMakerStudioLab: 'Amazon SageMaker Studio Lab',
  AmazonTextract: 'Amazon Textract',
  AmazonTranscribe: 'Amazon Transcribe',
  AmazonTranslate: 'Amazon Translate',
  ApacheMXNetonAWS: 'Apache MX Net on AWS',
  AWSAppStudio: 'AWS Studio',
  AWSDeepComposer: 'AWS DeepComposer',
  AWSDeepLearningAMIs: 'AWS Deep Learning AMIs',
  AWSDeepLearningContainers: 'AWS Deep Learning Containers',
  AWSDeepLens: 'AWS Deep Lens',
  AWSDeepRacer: 'AWS DeepRacer',
  AWSHealthImaging: 'AWS Health Imaging',
  AWSHealthLake: 'AWS Health Lake',
  AWSHealthOmics: 'AWS Health Omics',
  AWSHealthScribe: 'AWS Health Scribe',
  AWSNeuron: 'AWS Neuron',
  AWSPanorama: 'AWS Panorama',
  PyTorchonAWS: 'Py Torchon AWS',
  TensorFlowonAWS: 'Tensor Flowon AWS',
  AmazonManagedBlockchain: 'Amazon Managed Blockchain',
  AmazonQuantumLedgerDatabase: 'Amazon Quantum Ledger Database',
  AlexaForBusiness: 'Alexa For Business',
  AmazonChime: 'Amazon Chime',
  AmazonChimeSDK: 'Amazon Chime SDK',
  AmazonConnect: 'Amazon Connect',
  AmazonPinpoint: 'Amazon Pinpoint',
  AmazonPinpointAPIs: 'Amazon Pinpoint APIs',
  AmazonSimpleEmailService: 'Amazon Simple Email Service',
  AmazonWorkDocs: 'Amazon WorkDocs',
  AmazonWorkDocsSDK: 'Amazon WorkDocs SDK',
  AmazonWorkMail: 'Amazon WorkMail',
  AWSAppFabric: 'AWS App Fabric',
  AWSEndUserMessaging: 'AWS End User Messaging',
  AWSSupplyChain: 'AWS Supply Chain',
  AWSWickr: 'AWS Wickr',
  AWSBillingConductor: 'AWS Billing Conductor',
  AWSBudgets: 'AWS Budgets',
  AWSCostandUsageReport: 'AWS Costand Usage Report',
  AWSCostExplorer: 'AWS Cost Explorer',
  ReservedInstanceReporting: 'Reserved Instance Reporting',
  SavingsPlans: 'Savings Plans',
  AmazonDCV: 'Amazon DCV',
  AmazonEC2: 'Amazon EC2',
  AmazonEC2AutoScaling: 'Amazon EC2 Auto Scaling',
  AmazonEC2ImageBuilder: 'Amazon EC2 Image Builder',
  AmazonLightsail: 'Amazon Lightsail',
  AmazonLightsailforResearch: 'Amazon Lightsail for Research',
  AWSAppRunner: 'AWS App Runner',
  AWSBatch: 'AWS Batch',
  AWSComputeOptimizer: 'AWS Compute Optimizer',
  AWSElasticBeanstalk: 'AWS Elastic Beanstalk',
  AWSLambda: 'AWS Lambda',
  AWSLocalZones: 'AWS Local Zones',
  AWSNitroEnclaves: 'AWS Nitro Enclaves',
  AWSOutpostsfamily: 'AWS Outposts family',
  AWSOutpostsrack: 'AWS Outposts rack',
  AWSOutpostsservers: 'AWS Outposts servers',
  AWSParallelCluster: 'AWS Parallel Cluster',
  AWSParallelComputingService: 'AWS Parallel Computing Service',
  AWSServerlessApplicationRepository: 'AWS Serverless Application Repository',
  AWSSimSpaceWeaver: 'AWS Sim Space Weaver',
  AWSWavelength: 'AWS Wavelength',
  Bottlerocket: 'Bottlerocket',
  ElasticFabricAdapter: 'Elastic Fabric Adapter',
  NICEEnginFrame: 'NICE EnginFrame',
  AmazonECSAnywhere: 'Amazon ECS Anywhere',
  AmazonEKSAnywhere: 'Amazon EKS Anywhere',
  AmazonEKSCloud: 'Amazon EKS Cloud',
  AmazonEKSDistro: 'Amazon EKS Distro',
  AmazonElasticContainerRegistry: 'Amazon Elastic Container Registry',
  AmazonElasticContainerService: 'Amazon Elastic Container Service',
  AmazonElasticKubernetesService: 'Amazon Elastic Kubernetes Service',
  AWSFargate: 'AWS Fargate',
  RedHatOpenShiftServiceonAWS: 'Red Hat OpenShift Serviceon AWS',
  AWSActivate: 'AWS Activate',
  AWSIQ: 'AWS IQ',
  AWSManagedServices: 'AWS Managed Services',
  AWSProfessionalServices: 'AWS Professional Services',
  AWSrePost: 'AWS rePost',
  AWSrePostPrivate: 'AWS rePost Private',
  AWSSupport: 'AWS Support',
  AWSTrainingCertification: 'AWS Training Certification',
  AmazonAurora: 'Amazon Aurora',
  AmazonDocumentDB: 'Amazon DocumentDB',
  AmazonDynamoDB: 'Amazon DynamoDB',
  AmazonElastiCache: 'Amazon ElastiCache',
  AmazonKeyspaces: 'Amazon Keyspaces',
  AmazonMemoryDB: 'Amazon MemoryDB',
  AmazonNeptune: 'Amazon Neptune',
  AmazonRDS: 'Amazon RDS',
  AmazonTimestream: 'Amazon Timestream',
  AWSDatabaseMigrationService: 'AWS Database Migration Service',
  OracleDatabaseatAWS: 'Oracle Databaseat AWS',
  AmazonCodeCatalyst: 'Amazon Code Catalyst',
  AmazonCorretto: 'Amazon Corretto',
  AWSCloud9: 'AWS Cloud9',
  AWSCloudControlAPI: 'AWS Cloud Control API',
  AWSCloudDevelopmentKit: 'AWS Cloud Development Kit',
  AWSCloudShell: 'AWS CloudShell',
  AWSCodeArtifact: 'AWS CodeArtifact',
  AWSCodeBuild: 'AWS CodeBuild',
  AWSCodeCommit: 'AWS CodeCommit',
  AWSCodeDeploy: 'AWS CodeDeploy',
  AWSCodePipeline: 'AWS CodePipeline',
  AWSCommandLineInterface: 'AWS Command Line Interface',
  AWSFaultInjectionService: 'AWS Fault Injection Service',
  AWSInfrastructureComposer: 'AWS Infrastructure Composer',
  AWSToolsandSDKs: 'AWS Toolsand SDKs',
  AWSXRay: 'AWS XRay',
  AmazonAppStream2: 'Amazon AppStream2',
  AmazonWorkSpacesFamily: 'Amazon Work Spaces Family',
  AmazonLocationService: 'Amazon Location Service',
  AWSAmplify: 'AWS Amplify',
  AWSDeviceFarm: 'AWS Device Farm',
  AmazonGameLift: 'Amazon Game Lift',
  Open3DEngine: 'Open3DEngine',
  AWSMarketplace: 'AWS Marketplace',
  AWSMarketplaceDark: 'AWS Marketplace Dark',
  AWSIoTAnalytics: 'AWS IoT Analytics',
  AWSIoTButton: 'AWS IoT Button',
  AWSIoTCore: 'AWS IoT Core',
  AWSIoTDeviceDefender: 'AWS IoT Device Defender',
  AWSIoTDeviceManagement: 'AWS IoT Device Management',
  AWSIoTEvents: 'AWS IoT Events',
  AWSIoTExpressLink: 'AWS IoT ExpressLink',
  AWSIoTFleetWise: 'AWS IoT FleetWise',
  AWSIoTGreengrass: 'AWS IoT Greengrass',
  AWSIoTSiteWise: 'AWS IoT SiteWise',
  AWSIoTTwinMaker: 'AWS IoT TwinMaker',
  FreeRTOS: 'Free RTOS',
  AmazonCloudWatch: 'Amazon CloudWatch',
  AmazonManagedGrafana: 'Amazon Managed Grafana',
  AmazonManagedServiceforPrometheus: 'Amazon Managed Service for Prometheus',
  AWSAppConfig: 'AWS AppConfig',
  AWSApplicationAutoScaling: 'AWS Application Auto Scaling',
  AWSAutoScaling: 'AWS Auto Scaling',
  AWSBackintAgent: 'AWS Backint Agent',
  AWSChatbot: 'AWS Chatbot',
  AWSCloudFormation: 'AWS CloudFormation',
  AWSCloudTrail: 'AWS CloudTrail',
  AWSConfig: 'AWS Config',
  AWSConsoleMobileApplication: 'AWS Console Mobile Application',
  AWSControlTower: 'AWS Control Tower',
  AWSDistroforOpenTelemetry: 'AWS Distro for Open Telemetry',
  AWSHealthDashboard: 'AWS Health Dashboard',
  AWSLaunchWizard: 'AWS Launch Wizard',
  AWSLicenseManager: 'AWS License Manager',
  AWSManagementConsole: 'AWS Management Console',
  AWSOrganizations: 'AWS Organizations',
  AWSProton: 'AWS Proton',
  AWSResilienceHub: 'AWS Resilience Hub',
  AWSResourceExplorer: 'AWS Resource Explorer',
  AWSServiceCatalog: 'AWS Service Catalog',
  AWSServiceManagementConnector: 'AWS Service Management Connector',
  AWSSystemsManager: 'AWS Systems Manager',
  AWSTelcoNetworkBuilder: 'AWS Telco Network Builder',
  AWSTrustedAdvisor: 'AWS Trusted Advisor',
  AWSUserNotifications: 'AWS User Notifications',
  AWSWellArchitectedTool: 'AWS Well Architected Tool',
  AmazonElasticTranscoder: 'Amazon Elastic Transcoder',
  AmazonInteractiveVideoService: 'Amazon Interactive Video Service',
  AWSDeadlineCloud: 'AWS Deadline Cloud',
  AWSElementalAppliancesSoftware: 'AWS Elemental Appliances Software',
  AWSElementalConductor: 'AWS Elemental Conductor',
  AWSElementalDelta: 'AWS Elemental Delta',
  AWSElementalLink: 'AWS Elemental Link',
  AWSElementalLive: 'AWS Elemental Live',
  AWSElementalMediaConnect: 'AWS Elemental MediaConnect',
  AWSElementalMediaConvert: 'AWS Elemental MediaConvert',
  AWSElementalMediaLive: 'AWS Elemental MediaLive',
  AWSElementalMediaPackage: 'AWS Elemental MediaPackage',
  AWSElementalMediaStore: 'AWS Elemental MediaStore',
  AWSElementalMediaTailor: 'AWS Elemental MediaTailor',
  AWSElementalServer: 'AWS Elemental Server',
  AWSThinkboxDeadline: 'AWS Thinkbox Deadline',
  AWSThinkboxFrost: 'AWS Thinkbox Frost',
  AWSThinkboxKrakatoa: 'AWS Thinkbox Krakatoa',
  AWSThinkboxSequoia: 'AWS Thinkbox Sequoia',
  AWSThinkboxStoke: 'AWS Thinkbox Stoke',
  AWSThinkboxXMesh: 'AWS Thinkbox XMesh',
  AmazonElasticVMwareService: 'Amazon Elastic VMware Service',
  AWSApplicationDiscoveryService: 'AWS Application Discovery Service',
  AWSApplicationMigrationService: 'AWS Application Migration Service',
  AWSDataSync: 'AWS DataSync',
  AWSDataTransferTerminal: 'AWS Data Transfer Terminal',
  AWSMainframeModernization: 'AWS Mainframe Modernization',
  AWSMigrationEvaluator: 'AWS Migration Evaluator',
  AWSMigrationHub: 'AWS Migration Hub',
  AWSTransferFamily: 'AWS Transfer Family',
  AmazonAPIGateway: 'Amazon API Gateway',
  AmazonApplicationRecoveryController: 'Amazon Application Recovery Controller',
  AmazonCloudFront: 'Amazon CloudFront',
  AmazonRoute53: 'Amazon Route 53',
  AmazonVirtualPrivateCloud: 'Amazon Virtual Private Cloud',
  AmazonVPCLattice: 'Amazon VPC Lattice',
  AWSAppMesh: 'AWS App Mesh',
  AWSClientVPN: 'AWS Client VPN',
  AWSCloudMap: 'AWS Cloud Map',
  AWSCloudWAN: 'AWS Cloud WAN',
  AWSDirectConnect: 'AWS Direct Connect',
  AWSGlobalAccelerator: 'AWS Global Accelerator',
  AWSPrivate5G: 'AWS Private5G',
  AWSPrivateLink: 'AWS Private Link',
  AWSSitetoSiteVPN: 'AWS Siteto Site VPN',
  AWSTransitGateway: 'AWS Transit Gateway',
  AWSVerifiedAccess: 'AWS Verified Access',
  ElasticLoadBalancing: 'Elastic Load Balancing',
  AmazonBraket: 'Amazon Braket',
  AWSRoboMaker: 'AWS Robo Maker',
  AWSGroundStation: 'AWS Ground Station',
  AmazonCloudDirectory: 'Amazon Cloud Directory',
  AmazonCognito: 'Amazon Cognito',
  AmazonDetective: 'Amazon Detective',
  AmazonGuardDuty: 'Amazon Guard Duty',
  AmazonInspector: 'Amazon Inspector',
  AmazonMacie: 'Amazon Macie',
  AmazonSecurityLake: 'Amazon Security Lake',
  AmazonVerifiedPermissions: 'Amazon Verified Permissions',
  AWSArtifact: 'AWS Artifact',
  AWSAuditManager: 'AWS Audit Manager',
  AWSCertificateManager: 'AWS Certificate Manager',
  AWSCloudHSM: 'AWS CloudHSM',
  AWSDirectoryService: 'AWS Directory Service',
  AWSFirewallManager: 'AWS Firewall Manager',
  AWSIAMIdentityCenter: 'AWS IAM Identity Center',
  AWSIdentityandAccessManagement: 'AWS Identity and Access Management',
  AWSKeyManagementService: 'AWS Key Management Service',
  AWSNetworkFirewall: 'AWS Network Firewall',
  AWSPaymentCryptography: 'AWS Payment Cryptography',
  AWSPrivateCertificateAuthority: 'AWS Private Certificate Authority',
  AWSResourceAccessManager: 'AWS Resource Access Manager',
  AWSSecretsManager: 'AWS Secrets Manager',
  AWSSecurityHub: 'AWS Security Hub',
  AWSSecurityIncidentResponse: 'AWS Security Incident Response',
  AWSShield: 'AWS Shield',
  AWSSigner: 'AWS Signer',
  AWSWAF: 'AWS WAF',
  AmazonEFS: 'Amazon EFS',
  AmazonElasticBlockStore: 'Amazon Elastic Block Store',
  AmazonFileCache: 'Amazon File Cache',
  AmazonFSx: 'Amazon FSx',
  AmazonFSxforLustre: 'Amazon FSx for Lustre',
  AmazonFSxforNetAppONTAP: 'Amazon FSx for Net App ONTAP',
  AmazonFSxforOpenZFS: 'Amazon FSx for Open ZFS',
  AmazonFSxforWFS: 'Amazon FSx for WFS',
  AmazonS3onOutposts: 'Amazon S3 on Outposts',
  AmazonSimpleStorageService: 'Amazon Simple Storage Service',
  AmazonSimpleStorageServiceGlacier: 'Amazon Simple Storage Service Glacier',
  AWSBackup: 'AWS Backup',
  AWSElasticDisasterRecovery: 'AWS Elastic Disaster Recovery',
  AWSSnowball: 'AWS Snowball',
  AWSSnowballEdge: 'AWS Snowball Edge',
  AWSStorageGateway: 'AWS Storage Gateway',
} as Record<string, string>
